#!/bin/bash -eux
URL=${PWD##*/}
db_container_name=`echo ${URL}_db_1 | sed "s/\.//g"`; \

docker exec $db_container_name bash -c 'mysqldump --all-databases --events -p$MYSQL_ROOT_PASSWORD > /dump/dump.sql'
