#!/bin/bash -eux

MYSQL_ROOT_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`
ETHERPAD_ADMIN_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`

echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" > env
echo "ETHERPAD_ADMIN_PASSWORD=${ETHERPAD_ADMIN_PASSWORD}" >> env
